name: documentation.yml
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      pages: 'write'
      id-token: 'write'
    steps:
      - name: Clona repositório no servidor remoto do GitHub
        uses: actions/checkout@v5
        
      - name: Configura o interpretador Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Instala bibliotecas Python
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
          
      - name: Constrói páginas HTML com MKDocs
        run: mkdocs build
        
      - name: Transfere páginas HTML para o GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/'

      - name: Publica páginas HTML
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
